# Generated by Django 3.2.14 on 2022-07-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='author',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='content',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='title',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='closing_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='Restaurant', max_length=250),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Restaurant', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_time',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedme.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
                ('booking_date_time_start', models.DateTimeField()),
                ('booking_date_time_end', models.DateTimeField()),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedme.table')),
            ],
        ),
    ]
