# Generated by Django 3.2.14 on 2022-07-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0003_auto_20220720_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Costumer', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
