# Generated by Django 3.2.14 on 2022-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0004_costumer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
        migrations.RemoveField(
            model_name='table',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='booking',
            name='costumer',
            field=models.TextField(default='costumer', max_length=250),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='email', max_length=250),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
