# Generated by Django 3.2.14 on 2022-07-25 11:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feedme.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedme', '0005_auto_20220725_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(blank=True, null=True, validators=[feedme.models.Booking.validate_date]),
        ),
        migrations.AddField(
            model_name='booking',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'customer', 'booking_date_time')},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date_time_end',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date_time_start',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='costumer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
