# Generated by Django 3.2.14 on 2022-07-25 14:23

from django.db import migrations, models
import feedme.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0006_auto_20220725_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(null=True, validators=[feedme.models.Booking.validate_date]),
        ),
    ]
