# Generated by Django 3.2.14 on 2022-07-26 13:28

from django.db import migrations, models
import feedme.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0007_alter_booking_booking_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(blank=True, null=True, validators=[feedme.models.Booking.validate_date]),
        ),
    ]
