# Generated by Django 3.2.14 on 2022-07-27 08:43

from django.db import migrations, models
import feedme.models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0009_auto_20220727_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateField(blank=True, null=True, validators=[feedme.models.Booking.validate_date]),
        ),
    ]
