# Generated by Django 3.2.14 on 2022-07-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedme', '0012_alter_booking_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(null=True),
        ),
    ]
