# Generated by Django 3.2.14 on 2022-07-28 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedme', '0014_auto_20220728_1545'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='user_bookingdate_unique',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'booking_date')},
        ),
    ]
