# Generated by Django 3.2.14 on 2022-07-29 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedme', '0015_auto_20220728_1550'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'booking_date', 'booking_time')},
        ),
    ]
